---
- name: "Set role variables"
  ansible.builtin.set_fact:
    brewfile_location: "$HOME/.brewfile.ios-dev"

- name: "Link brewfile into home directory"
  ansible.builtin.copy:
    src: "files/brewfile.ios"
    dest: "{{ brewfile_location }}"
    mode: "0644"

- name: "Install from Brewfile"
  command: "{{ ios_homebrew_brew_bin_path }}/brew bundle --file={{ brewfile_location }}"